// Font loading
//
#include "fonts/8x13/u000000-u0000FF.xbm"
#include "fonts/8x13/u000100-u0001FF.xbm"
#include "fonts/8x13/u000200-u0002FF.xbm"
#include "fonts/8x13/u000300-u0003FF.xbm"
#include "fonts/8x13/u000400-u0004FF.xbm"
#include "fonts/8x13/u000500-u0005FF.xbm"
#include "fonts/8x13/u000E00-u000EFF.xbm"
#include "fonts/8x13/u001000-u0010FF.xbm"
#include "fonts/8x13/u001600-u0016FF.xbm"
#include "fonts/8x13/u001E00-u001EFF.xbm"
#include "fonts/8x13/u001F00-u001FFF.xbm"
#include "fonts/8x13/u002000-u0020FF.xbm"
#include "fonts/8x13/u002100-u0021FF.xbm"
#include "fonts/8x13/u002200-u0022FF.xbm"
#include "fonts/8x13/u002300-u0023FF.xbm"
#include "fonts/8x13/u002400-u0024FF.xbm"
#include "fonts/8x13/u002500-u0025FF.xbm"
#include "fonts/8x13/u002600-u0026FF.xbm"
#include "fonts/8x13/u002700-u0027FF.xbm"
#include "fonts/8x13/u002800-u0028FF.xbm"
#include "fonts/8x13/u002A00-u002AFF.xbm"
#include "fonts/8x13/u003000-u0030FF.xbm"
#include "fonts/8x13/u00FB00-u00FBFF.xbm"
#include "fonts/8x13/u00FE00-u00FEFF.xbm"
#include "fonts/8x13/u00FF00-u00FFFF.xbm"
//
static void load(BuiltinFonts& builtinFonts)
{
  builtinFonts.loadXbmFont(Font::MISC_MISC_8x13, 0x000000u,
                            u000000_u0000FF_width,
                            u000000_u0000FF_height,
                            u000000_u0000FF_bits);
  builtinFonts.loadXbmFont(Font::MISC_MISC_8x13, 0x000100u,
                            u000100_u0001FF_width,
                            u000100_u0001FF_height,
                            u000100_u0001FF_bits);
  builtinFonts.loadXbmFont(Font::MISC_MISC_8x13, 0x000200u,
                            u000200_u0002FF_width,
                            u000200_u0002FF_height,
                            u000200_u0002FF_bits);
  builtinFonts.loadXbmFont(Font::MISC_MISC_8x13, 0x000300u,
                            u000300_u0003FF_width,
                            u000300_u0003FF_height,
                            u000300_u0003FF_bits);
  builtinFonts.loadXbmFont(Font::MISC_MISC_8x13, 0x000400u,
                            u000400_u0004FF_width,
                            u000400_u0004FF_height,
                            u000400_u0004FF_bits);
  builtinFonts.loadXbmFont(Font::MISC_MISC_8x13, 0x000500u,
                            u000500_u0005FF_width,
                            u000500_u0005FF_height,
                            u000500_u0005FF_bits);
  builtinFonts.loadXbmFont(Font::MISC_MISC_8x13, 0x000E00u,
                            u000E00_u000EFF_width,
                            u000E00_u000EFF_height,
                            u000E00_u000EFF_bits);
  builtinFonts.loadXbmFont(Font::MISC_MISC_8x13, 0x001000u,
                            u001000_u0010FF_width,
                            u001000_u0010FF_height,
                            u001000_u0010FF_bits);
  builtinFonts.loadXbmFont(Font::MISC_MISC_8x13, 0x001600u,
                            u001600_u0016FF_width,
                            u001600_u0016FF_height,
                            u001600_u0016FF_bits);
  builtinFonts.loadXbmFont(Font::MISC_MISC_8x13, 0x001E00u,
                            u001E00_u001EFF_width,
                            u001E00_u001EFF_height,
                            u001E00_u001EFF_bits);
  builtinFonts.loadXbmFont(Font::MISC_MISC_8x13, 0x001F00u,
                            u001F00_u001FFF_width,
                            u001F00_u001FFF_height,
                            u001F00_u001FFF_bits);
  builtinFonts.loadXbmFont(Font::MISC_MISC_8x13, 0x002000u,
                            u002000_u0020FF_width,
                            u002000_u0020FF_height,
                            u002000_u0020FF_bits);
  builtinFonts.loadXbmFont(Font::MISC_MISC_8x13, 0x002100u,
                            u002100_u0021FF_width,
                            u002100_u0021FF_height,
                            u002100_u0021FF_bits);
  builtinFonts.loadXbmFont(Font::MISC_MISC_8x13, 0x002200u,
                            u002200_u0022FF_width,
                            u002200_u0022FF_height,
                            u002200_u0022FF_bits);
  builtinFonts.loadXbmFont(Font::MISC_MISC_8x13, 0x002300u,
                            u002300_u0023FF_width,
                            u002300_u0023FF_height,
                            u002300_u0023FF_bits);
  builtinFonts.loadXbmFont(Font::MISC_MISC_8x13, 0x002400u,
                            u002400_u0024FF_width,
                            u002400_u0024FF_height,
                            u002400_u0024FF_bits);
  builtinFonts.loadXbmFont(Font::MISC_MISC_8x13, 0x002500u,
                            u002500_u0025FF_width,
                            u002500_u0025FF_height,
                            u002500_u0025FF_bits);
  builtinFonts.loadXbmFont(Font::MISC_MISC_8x13, 0x002600u,
                            u002600_u0026FF_width,
                            u002600_u0026FF_height,
                            u002600_u0026FF_bits);
  builtinFonts.loadXbmFont(Font::MISC_MISC_8x13, 0x002700u,
                            u002700_u0027FF_width,
                            u002700_u0027FF_height,
                            u002700_u0027FF_bits);
  builtinFonts.loadXbmFont(Font::MISC_MISC_8x13, 0x002800u,
                            u002800_u0028FF_width,
                            u002800_u0028FF_height,
                            u002800_u0028FF_bits);
  builtinFonts.loadXbmFont(Font::MISC_MISC_8x13, 0x002A00u,
                            u002A00_u002AFF_width,
                            u002A00_u002AFF_height,
                            u002A00_u002AFF_bits);
  builtinFonts.loadXbmFont(Font::MISC_MISC_8x13, 0x003000u,
                            u003000_u0030FF_width,
                            u003000_u0030FF_height,
                            u003000_u0030FF_bits);
  builtinFonts.loadXbmFont(Font::MISC_MISC_8x13, 0x00FB00u,
                            u00FB00_u00FBFF_width,
                            u00FB00_u00FBFF_height,
                            u00FB00_u00FBFF_bits);
  builtinFonts.loadXbmFont(Font::MISC_MISC_8x13, 0x00FE00u,
                            u00FE00_u00FEFF_width,
                            u00FE00_u00FEFF_height,
                            u00FE00_u00FEFF_bits);
  builtinFonts.loadXbmFont(Font::MISC_MISC_8x13, 0x00FF00u,
                            u00FF00_u00FFFF_width,
                            u00FF00_u00FFFF_height,
                            u00FF00_u00FFFF_bits);
}
